import 'dart:io';

void main() {
  final dir = Directory('d:/zenvi/frontend_pos/lib');
  
  // Mapping original string -> key
  final Map<String, String> stringToKey = {
    'Perusahaan berhasil dibuat!': 'perusahaan_berhasil_dibuat_0',
    'Gagal membuat perusahaan. Silakan coba lagi.': 'gagal_membuat_perusahaan_silakan_1',
    'Setup Perusahaan': 'setup_perusahaan_2',
    'Satu Langkah Lagi!': 'satu_langkah_lagi_3',
    'Buat nama perusahaan/toko Anda untuk mulai menggunakan Zenvi POS dan menikmati fitur seperti Chat, Cabang, dan Shift.': 'buat_nama_perusahaantoko_anda_4',
    'Aktifkan Kitchen Display System (KDS)': 'aktifkan_kitchen_display_system_5',
    'Tampilkan layar khusus dapur untuk pesanan yang masuk.': 'tampilkan_layar_khusus_dapur_6',
    'Buat Perusahaan': 'buat_perusahaan_7',
    'Nama Perusahaan': 'nama_perusahaan_8',
    'Harap pilih cabang tempat Anda bertugas.': 'harap_pilih_cabang_tempat_9',
    'Permohonan berhasil dikirim! Menunggu persetujuan Owner.': 'permohonan_berhasil_dikirim_menunggu_10',
    'Gagal mengirim permohonan. Silakan coba lagi.': 'gagal_mengirim_permohonan_silakan_11',
    'Gabung ke Toko': 'gabung_ke_toko_12',
    'Masukkan Kode Toko yang diberikan oleh Owner tempat Anda bekerja untuk bergabung.': 'masukkan_kode_toko_yang_13',
    'Pilih Cabang Penempatan:': 'pilih_cabang_penempatan_14',
    'Cabang Utama (Default)': 'cabang_utama_default_15',
    'Kode Toko': 'kode_toko_16',
    'Contoh: ZNV-8821': 'contoh_znv8821_17',
    'OR': 'or_18',
    'System will automatically detect your store status & access permissions.': 'system_will_automatically_detect_19',
    'Permohonan Anda ditolak atau belum terhubung ke toko.': 'permohonan_anda_ditolak_atau_20',
    'Status masih menunggu persetujuan dari Owner.': 'status_masih_menunggu_persetujuan_21',
    'Batalkan Pendaftaran?': 'batalkan_pendaftaran_22',
    'Apakah Anda yakin ingin membatalkan permohonan bergabung ke toko ini? Anda dapat memilih toko atau peran lain setelah ini.': 'apakah_anda_yakin_ingin_23',
    'Kembali': 'kembali_24',
    'Ya, Batalkan': 'ya_batalkan_25',
    'Pendaftaran dibatalkan.': 'pendaftaran_dibatalkan_26',
    'Gagal membatalkan permohonan. Silakan coba lagi.': 'gagal_membatalkan_permohonan_silakan_27',
    'Status Pendaftaran': 'status_pendaftaran_28',
    'Menunggu Verifikasi Owner': 'menunggu_verifikasi_owner_29',
    'Permohonan Anda sedang ditinjau oleh Owner toko. Begitu disetujui, Anda langsung dapat mulai bekerja.': 'permohonan_anda_sedang_ditinjau_30',
    'Batalkan Pendaftaran / Ganti Toko': 'batalkan_pendaftaran_ganti_toko_31',
    'Konfirmasi Keluar': 'konfirmasi_keluar_32',
    'Apakah Anda yakin ingin keluar dari akun ini?': 'apakah_anda_yakin_ingin_33',
    'Pilih peran Anda untuk mulai menggunakan Zenvi POS.': 'pilih_peran_anda_untuk_34',
    'Anda dapat beralih peran atau membuat toko lain kapan saja.': 'anda_dapat_beralih_peran_35',
    'Mulai Sekarang': 'mulai_sekarang_36',
    'Pesan Internal': 'pesan_internal_37',
    'Grup Karyawan & Obrolan Pribadi': 'grup_karyawan_obrolan_pribadi_38',
    'Ketik pesan...': 'ketik_pesan_39',
    'Pastikan semua bahan baku dipilih dan takarannya valid!': 'pastikan_semua_bahan_baku_40',
    'Pastikan nama varian tidak kosong dan harga valid!': 'pastikan_nama_varian_tidak_41',
    'Gagal menyimpan produk': 'gagal_menyimpan_produk_42',
    'Foto Produk': 'foto_produk_43',
    'Unggah Foto (1:1)': 'unggah_foto_11_44',
    'Informasi Dasar': 'informasi_dasar_45',
    'Saran: ': 'saran_46',
    'Diskon (Opsional)': 'diskon_opsional_47',
    'Varian (Opsional)': 'varian_opsional_48',
    'Tambah': 'tambah_49',
    'Tidak ada varian ditambahkan.': 'tidak_ada_varian_ditambahkan_50',
    'Bahan Baku / Resep': 'bahan_baku_resep_51',
    'Bahan baku akan terpotong otomatis saat produk terjual.': 'bahan_baku_akan_terpotong_52',
    'Belum ada bahan baku yang dipilih.': 'belum_ada_bahan_baku_53',
    'Pilih Bahan': 'pilih_bahan_54',
    'Tampilkan di Kasir': 'tampilkan_di_kasir_55',
    'Produk dapat dibeli jika aktif': 'produk_dapat_dibeli_jika_56',
    'Nama Produk': 'nama_produk_57',
    'Kategori (Opsional)': 'kategori_opsional_58',
    'Harga Jual (Rp)': 'harga_jual_rp_59',
    'Nominal (Rp)': 'nominal_rp_60',
    'Persen (%)': 'persen_61',
    'Contoh: Makanan, Minuman...': 'contoh_makanan_minuman_62',
    'Nama Varian': 'nama_varian_63',
    'Harga Tambahan': 'harga_tambahan_64',
    'Takaran': 'takaran_65',
    'Menu Operasional': 'menu_operasional_66',
    'Coba Lagi': 'coba_lagi_67',
    'Performa Karyawan': 'performa_karyawan_68',
    'Urut: Omzet Tertinggi': 'urut_omzet_tertinggi_69',
    'Belum ada data karyawan atau transaksi pada periode ini.': 'belum_ada_data_karyawan_70',
    'Ringkasan Kinerja Tim': 'ringkasan_kinerja_tim_71',
    'Total Penjualan Tim': 'total_penjualan_tim_72',
    'Total Transaksi Selesai': 'total_transaksi_selesai_73',
    'Performa Terbaik (Leaderboard)': 'performa_terbaik_leaderboard_74',
    'Rincian Pembayaran Transaksi:': 'rincian_pembayaran_transaksi_75',
    'Disiplin Absensi & Kehadiran:': 'disiplin_absensi_kehadiran_76',
    'Riwayat Shift Terakhir': 'riwayat_shift_terakhir_77',
    'Belum ada riwayat shift': 'belum_ada_riwayat_shift_78',
    'Pilih Template Peran (Preset)': 'pilih_template_peran_preset_79',
    'Modul & Fitur yang Dapat Diakses': 'modul_fitur_yang_dapat_80',
    'Fitur Absensi & Chat selalu aktif untuk semua karyawan agar performa & kehadiran tetap tercatat.': 'fitur_absensi_chat_selalu_81',
    'Gagal menyetujui karyawan.': 'gagal_menyetujui_karyawan_82',
    'Gagal memperbarui hak akses.': 'gagal_memperbarui_hak_akses_83',
    'Tolak Pendaftar': 'tolak_pendaftar_84',
    'Tolak': 'tolak_85',
    'Gagal menolak pendaftaran.': 'gagal_menolak_pendaftaran_86',
    'Hapus Karyawan': 'hapus_karyawan_87',
    'Hapus': 'hapus_88',
    'Gagal menghapus karyawan.': 'gagal_menghapus_karyawan_89',
    'Setujui': 'setujui_90',
    'Kelola Tim & Hak Akses': 'kelola_tim_hak_akses_91',
    'Atur peran modular untuk kasir, staf, dapur & gudang': 'atur_peran_modular_untuk_92',
    'Kode Toko Anda:': 'kode_toko_anda_93',
    'Salin': 'salin_94',
    'Nama Jabatan / Posisi': 'nama_jabatan_posisi_95',
    'Contoh: Kasir Utama, Kapster Senior, Barista': 'contoh_kasir_utama_kapster_96',
    'Catat Pengeluaran Baru': 'catat_pengeluaran_baru_97',
    'Order Bahan (Restock)': 'order_bahan_restock_98',
    'Gaji Karyawan': 'gaji_karyawan_99',
    'Operasional / Lainnya': 'operasional_lainnya_100',
    'Total biaya tidak valid': 'total_biaya_tidak_valid_101',
    'Pilih bahan baku': 'pilih_bahan_baku_102',
    'Kuantitas tidak valid': 'kuantitas_tidak_valid_103',
    'Pengeluaran berhasil dicatat': 'pengeluaran_berhasil_dicatat_104',
    'Simpan Pengeluaran': 'simpan_pengeluaran_105',
    'Catat Pengeluaran': 'catat_pengeluaran_106',
    'Catatan Pengeluaran': 'catatan_pengeluaran_107',
    'Belum ada pengeluaran tercatat': 'belum_ada_pengeluaran_tercatat_108',
    'Jenis Pengeluaran': 'jenis_pengeluaran_109',
    'Pilih Bahan Baku': 'pilih_bahan_baku_110',
    'Jumlah Kuantitas (Stok Bertambah)': 'jumlah_kuantitas_stok_bertambah_111',
    'Total Biaya (Rp)': 'total_biaya_rp_112',
    'Keterangan (Opsional)': 'keterangan_opsional_113',
    'Tambah Bahan Baku': 'tambah_bahan_baku_114',
    'Bahan baku ditambahkan!': 'bahan_baku_ditambahkan_115',
    'Manajemen Bahan': 'manajemen_bahan_116',
    'Peringatan Indikasi Fraud!': 'peringatan_indikasi_fraud_117',
    'Edit': 'edit_118',
    'Nama Bahan (misal: Gula)': 'nama_bahan_misal_gula_119',
    'Satuan (misal: gram, ml, pcs)': 'satuan_misal_gram_ml_120',
    'Stok Awal': 'stok_awal_121',
    'Toleransi Susut (%)': 'toleransi_susut_122',
    'Catat biaya operasional, gaji, atau order bahan': 'catat_biaya_operasional_gaji_123',
    'Operasional / Tagihan / Listrik': 'operasional_tagihan_listrik_124',
    'Order Bahan (Restock Stok)': 'order_bahan_restock_stok_125',
    'Pengeluaran Lainnya': 'pengeluaran_lainnya_126',
    'Nominal biaya tidak valid': 'nominal_biaya_tidak_valid_127',
    'Pilih bahan baku terlebih dahulu': 'pilih_bahan_baku_terlebih_128',
    'Jumlah kuantitas tidak valid': 'jumlah_kuantitas_tidak_valid_129',
    'Pengeluaran berhasil dicatat & data diperbarui': 'pengeluaran_berhasil_dicatat_data_130',
    'Pilih Tanggal Laporan': 'pilih_tanggal_laporan_131',
    'Filter ringkasan finansial dan grafik performa': 'filter_ringkasan_finansial_dan_132',
    'Filter Cepat': 'filter_cepat_133',
    'Pilih Satu Tanggal Spesifik': 'pilih_satu_tanggal_spesifik_134',
    'Pilih Rentang Tanggal (Kustom)': 'pilih_rentang_tanggal_kustom_135',
    'Tutup': 'tutup_136',
    'OWNER PORTAL': 'owner_portal_137',
    'Pilih Cabang': 'pilih_cabang_138',
    'Pelanggan telah mengajukan reservasi via web. Ketuk untuk meninjau.': 'pelanggan_telah_mengajukan_reservasi_139',
    'Laporan & Analisis': 'laporan_analisis_140',
    'Tren Omzet & Laba': 'tren_omzet_laba_141',
    'Perbandingan omzet vs beban pengeluaran': 'perbandingan_omzet_vs_beban_142',
    'Tidak ada data transaksi pada rentang ini.': 'tidak_ada_data_transaksi_143',
    'Analisis Jam Sibuk': 'analisis_jam_sibuk_144',
    '24 Jam': '24_jam_145',
    'Distribusi penjualan berdasarkan jam transaksi': 'distribusi_penjualan_berdasarkan_jam_146',
    'Belum ada data transaksi.': 'belum_ada_data_transaksi_147',
    'Metode Pembayaran': 'metode_pembayaran_148',
    'Proporsi transaksi berdasarkan cara bayar': 'proporsi_transaksi_berdasarkan_cara_149',
    'Belum ada transaksi.': 'belum_ada_transaksi_150',
    'Menu Terlaris (Top 5)': 'menu_terlaris_top_5_151',
    '5 Menu paling banyak terjual pada periode ini': '5_menu_paling_banyak_152',
    'Belum ada data penjualan produk.': 'belum_ada_data_penjualan_153',
    'Performa Antar Cabang': 'performa_antar_cabang_154',
    'Belum ada data cabang.': 'belum_ada_data_cabang_155',
    'Log Kasir & Shift': 'log_kasir_shift_156',
    'Lihat Semua': 'lihat_semua_157',
    'Belum ada shift kasir yang tercatat pada rentang ini.': 'belum_ada_shift_kasir_158',
    'Aksi Cepat': 'aksi_cepat_159',
    'Kelola Bisnis': 'kelola_bisnis_160',
    'Eksplorasi Semua Fitur': 'eksplorasi_semua_fitur_161',
    'Jumlah Kuantitas Dibeli (Stok Bertambah)': 'jumlah_kuantitas_dibeli_stok_162',
    'Nominal Biaya (Rp)': 'nominal_biaya_rp_163',
    'Log Transaksi': 'log_transaksi_164',
    'Pantau transaksi dari seluruh cabang': 'pantau_transaksi_dari_seluruh_165',
    'Belum ada transaksi sesuai filter.': 'belum_ada_transaksi_sesuai_166',
    'VOID': 'void_167',
    'Daftar Produk': 'daftar_produk_168',
    'Belum ada produk': 'belum_ada_produk_169',
    'Tambahkan produk untuk mulai berjualan': 'tambahkan_produk_untuk_mulai_170',
    'Edit Produk': 'edit_produk_171',
    'Tambah Produk': 'tambah_produk_172',
    'Log Shift Karyawan': 'log_shift_karyawan_173',
    'Belum Ada Data Shift': 'belum_ada_data_shift_174',
    'Riwayat buka dan tutup shift kasir akan tercatat secara otomatis di sini.': 'riwayat_buka_dan_tutup_175',
    'Kas Laci Fisik (Kasir):': 'kas_laci_fisik_kasir_176',
    'Gagal memperbarui status pesanan.': 'gagal_memperbarui_status_pesanan_177',
    'Terjadi kesalahan jaringan.': 'terjadi_kesalahan_jaringan_178',
    'Kitchen Display System': 'kitchen_display_system_179',
    'Tidak ada pesanan dapur saat ini': 'tidak_ada_pesanan_dapur_180',
    'MULAI MASAK': 'mulai_masak_181',
    'SELESAI': 'selesai_182',
    'Membership': 'membership_183',
    'Tambah Member Baru': 'tambah_member_baru_184',
    'Nama dan No. Telepon wajib diisi!': 'nama_dan_no_telepon_185',
    'Hapus Member?': 'hapus_member_186',
    'Belum ada member terdaftar': 'belum_ada_member_terdaftar_187',
    'Tap + untuk menambah member baru': 'tap_untuk_menambah_member_188',
    'Buat Promo Member': 'buat_promo_member_189',
    'Persentase (%)': 'persentase_190',
    'Potongan Nominal (Rp)': 'potongan_nominal_rp_191',
    'Harga Tetap (Rp)': 'harga_tetap_rp_192',
    'Pilih Produk Berlaku:': 'pilih_produk_berlaku_193',
    'Nama dan nilai diskon wajib diisi': 'nama_dan_nilai_diskon_194',
    'Pilih minimal satu produk': 'pilih_minimal_satu_produk_195',
    'Promo berhasil dibuat!': 'promo_berhasil_dibuat_196',
    'Simpan Promo': 'simpan_promo_197',
    'Buat Promo': 'buat_promo_198',
    'Belum ada promo member': 'belum_ada_promo_member_199',
    'Buat promo khusus untuk member Anda': 'buat_promo_khusus_untuk_200',
    'Hapus Promo?': 'hapus_promo_201',
    'Nama Lengkap *': 'nama_lengkap_202',
    'No. WhatsApp / HP *': 'no_whatsapp_hp_203',
    'Email (opsional)': 'email_opsional_204',
    'Alamat (opsional)': 'alamat_opsional_205',
    'Diskon Khusus Member (%)': 'diskon_khusus_member_206',
    'Catatan (opsional)': 'catatan_opsional_207',
    'Nama Promo *': 'nama_promo_208',
    'Deskripsi': 'deskripsi_209',
    'Tipe Diskon': 'tipe_diskon_210',
    'Min. Pembelian (Rp)': 'min_pembelian_rp_211',
    'Misal: Budi Santoso': 'misal_budi_santoso_212',
    'Misal: 08123456789': 'misal_08123456789_213',
    'budi@example.com': 'budiexamplecom_214',
    '0 - 100': '0_100_215',
    'Cari nama, telepon, atau kode member...': 'cari_nama_telepon_atau_216',
    'Pusat Notifikasi': 'pusat_notifikasi_217',
    'Semua notifikasi ditandai dibaca': 'semua_notifikasi_ditandai_dibaca_218',
    'Baca Semua': 'baca_semua_219',
    'Buka': 'buka_220',
    'Belum Ada Notifikasi': 'belum_ada_notifikasi_221',
    'Pilih Sumber Foto Bukti': 'pilih_sumber_foto_bukti_222',
    'Ambil Foto dari Kamera': 'ambil_foto_dari_kamera_223',
    'Pilih dari Galeri': 'pilih_dari_galeri_224',
    'Mohon tuliskan alasan izin Anda.': 'mohon_tuliskan_alasan_izin_225',
    'Wajib melampirkan foto bukti surat/keadaan izin.': 'wajib_melampirkan_foto_bukti_226',
    'Pengajuan berhasil dikirim dengan Status: Menunggu Persetujuan (Pending).': 'pengajuan_berhasil_dikirim_dengan_227',
    'Pengajuan Izin Karyawan': 'pengajuan_izin_karyawan_228',
    'Informasi Privasi & Penyimpanan': 'informasi_privasi_penyimpanan_229',
    'Foto bukti yang Anda lampirkan akan otomatis dihapus permanen oleh server setelah 3 hari untuk efisiensi penyimpanan.': 'foto_bukti_yang_anda_230',
    'Jenis Pengajuan Izin': 'jenis_pengajuan_izin_231',
    'Tanggal Izin': 'tanggal_izin_232',
    'Perkiraan Jam Tiba di Toko': 'perkiraan_jam_tiba_di_233',
    'Alasan / Keterangan': 'alasan_keterangan_234',
    'Foto Bukti (Wajib Lampirkan)': 'foto_bukti_wajib_lampirkan_235',
    'Klik untuk Ambil Foto / Pilih Bukti': 'klik_untuk_ambil_foto_236',
    'Surat dokter, foto kondisi, atau surat izin resmi': 'surat_dokter_foto_kondisi_237',
    'Foto Bukti Terpilih': 'foto_bukti_terpilih_238',
    'Kirim Pengajuan Izin': 'kirim_pengajuan_izin_239',
    'Status Izin: 🟡 Menunggu (Proses Review) • 🟢 Disetujui (Absensi Sah) • 🔴 Ditolak': 'status_izin_menunggu_proses_240',
    'Pengajuan izin libur atau telat masuk yang Anda buat akan tercatat di sini.': 'pengajuan_izin_libur_atau_241',
    'Alasan Pengajuan:': 'alasan_pengajuan_242',
    'Lihat Foto Bukti (Aktif < 3 Hari)': 'lihat_foto_bukti_aktif_243',
    'Bukti lampiran telah kedaluwarsa & dihapus otomatis (3 hari).': 'bukti_lampiran_telah_kedaluwarsa_244',
    'Batalkan Pengajuan': 'batalkan_pengajuan_245',
    'Gagal memuat gambar atau bukti telah kedaluwarsa.': 'gagal_memuat_gambar_atau_246',
    'Batalkan Pengajuan?': 'batalkan_pengajuan_247',
    'Apakah Anda yakin ingin membatalkan dan menghapus pengajuan izin ini?': 'apakah_anda_yakin_ingin_248',
    'Contoh: Sakit demam dengan surat dokter / Ban bocor di jalan...': 'contoh_sakit_demam_dengan_249',
    'Persetujuan Izin': 'persetujuan_izin_250',
    'Tidak Ada Pengajuan Izin': 'tidak_ada_pengajuan_izin_251',
    'Saat ini belum ada pengajuan izin dari karyawan pada filter ini.': 'saat_ini_belum_ada_252',
    'Buka Foto Bukti Lampiran': 'buka_foto_bukti_lampiran_253',
    'Bukti lampiran telah terhapus otomatis oleh sistem (>3 hari).': 'bukti_lampiran_telah_terhapus_254',
    'Setujui Izin Karyawan?': 'setujui_izin_karyawan_255',
    'Pengajuan izin ini akan disetujui dan status absensi/keterlambatan karyawan akan disesuaikan secara otomatis.': 'pengajuan_izin_ini_akan_256',
    'Ya, Setujui': 'ya_setujui_257',
    'Tolak Pengajuan Izin': 'tolak_pengajuan_izin_258',
    'Tuliskan alasan penolakan untuk karyawan (opsional):': 'tuliskan_alasan_penolakan_untuk_259',
    'Tolak Izin': 'tolak_izin_260',
    'Contoh: Jadwal shift sudah padat / Dokumen kurang jelas': 'contoh_jadwal_shift_sudah_261',
    'Daftar Member Baru (Kasir)': 'daftar_member_baru_kasir_262',
    'Pilih Member': 'pilih_member_263',
    'Cari atau daftarkan member baru': 'cari_atau_daftarkan_member_264',
    'Daftarkan Member Baru': 'daftarkan_member_baru_265',
    'Misal: Rina Wijaya': 'misal_rina_wijaya_266',
    'rina@example.com': 'rinaexamplecom_267',
    'Cari member...': 'cari_member_268',
    'Detail Transaksi': 'detail_transaksi_269',
    'Void': 'void_270',
    'Share': 'share_271',
    'Cetak Nota': 'cetak_nota_272',
    'Konfirmasi Void': 'konfirmasi_void_273',
    'Apakah Anda yakin ingin membatalkan transaksi ini? Stok akan dikembalikan.': 'apakah_anda_yakin_ingin_274',
    'Ya, Void': 'ya_void_275',
    'Transaksi berhasil dibatalkan.': 'transaksi_berhasil_dibatalkan_276',
    'Gagal membatalkan transaksi.': 'gagal_membatalkan_transaksi_277',
    'Belum ada transaksi hari ini.': 'belum_ada_transaksi_hari_278',
    'Riwayat Transaksi': 'riwayat_transaksi_279',
    'Retry': 'retry_280',
    'Belum Sync': 'belum_sync_281',
    'Menu kosong atau belum tersinkronisasi.': 'menu_kosong_atau_belum_282',
    'Tidak ada produk yang cocok.': 'tidak_ada_produk_yang_283',
    'Reset Filter': 'reset_filter_284',
    'Point of Sale': 'point_of_sale_285',
    'Menyinkronkan data...': 'menyinkronkan_data_286',
    'Kosongkan Keranjang?': 'kosongkan_keranjang_287',
    'Semua produk di keranjang belanja akan dihapus.': 'semua_produk_di_keranjang_288',
    'Kosongkan': 'kosongkan_289',
    'Pilih Member / Pelanggan': 'pilih_member_pelanggan_290',
    'Subtotal': 'subtotal_291',
    'Diskon Member': 'diskon_member_292',
    'Total Pembayaran': 'total_pembayaran_293',
    'Belum Buka Shift': 'belum_buka_shift_294',
    'Anda belum membuka shift hari ini. Silakan buka shift terlebih dahulu di menu Shift untuk dapat menerima pembayaran.': 'anda_belum_membuka_shift_295',
    'Buka Shift Sekarang': 'buka_shift_sekarang_296',
    'Gagal memproses transaksi. Silakan coba lagi.': 'gagal_memproses_transaksi_silakan_297',
    'Tidak ada menu.': 'tidak_ada_menu_298',
    'Pilih Varian': 'pilih_varian_299',
    'Cari nama produk atau kategori...': 'cari_nama_produk_atau_300',
    'Selesai': 'selesai_301',
    'Buka Pengaturan Printer': 'buka_pengaturan_printer_302',
    'Pengaturan Printer Bluetooth': 'pengaturan_printer_bluetooth_303',
    'Putuskan': 'putuskan_304',
    'Tidak ada perangkat Bluetooth yang ditemukan.\\nPastikan Bluetooth HP nyala dan printer sudah di-pairing (disandingkan) lewat pengaturan HP.': 'tidak_ada_perangkat_bluetooth_305',
    'Berhasil terhubung!': 'berhasil_terhubung_306',
    'Gagal terhubung ke printer. Pastikan printer nyala.': 'gagal_terhubung_ke_printer_307',
    'Connect': 'connect_308',
    'Pilih cara pembayaran transaksi ini': 'pilih_cara_pembayaran_transaksi_309',
    'Total Tagihan': 'total_tagihan_310',
    'Pilihan Uang Cepat': 'pilihan_uang_cepat_311',
    'Pembayaran QRIS Digital': 'pembayaran_qris_digital_312',
    'Minta pelanggan memindai QRIS toko. Pastikan notifikasi dana masuk telah terkonfirmasi.': 'minta_pelanggan_memindai_qris_313',
    'Transfer Bank': 'transfer_bank_314',
    'Periksa bukti mutasi atau bukti transfer bank sebelum mengonfirmasi pesanan.': 'periksa_bukti_mutasi_atau_315',
    'Staf / Terapis / Kapster (Opsional)': 'staf_terapis_kapster_opsional_316',
    'Pilih staf yang melayani...': 'pilih_staf_yang_melayani_317',
    'Uang Diterima (Rp)': 'uang_diterima_rp_318',
    'Pembayaran Berhasil': 'pembayaran_berhasil_319',
    'Bagikan': 'bagikan_320',
    'Cetak Struk': 'cetak_struk_321',
    'Selesai & Transaksi Baru': 'selesai_transaksi_baru_322',
    'Struk Belanja': 'struk_belanja_323',
    'Detail item offline disembunyikan.': 'detail_item_offline_disembunyikan_324',
    'TOTAL': 'total_325',
    'Metode Bayar': 'metode_bayar_326',
    'Bayar Tunai': 'bayar_tunai_327',
    'Kembalian': 'kembalian_328',
    'Poin Diperoleh': 'poin_diperoleh_329',
    'Terima kasih telah berbelanja!': 'terima_kasih_telah_berbelanja_330',
    'Powered by Zenvi POS': 'powered_by_zenvi_pos_331',
    'Daftar Reservasi': 'daftar_reservasi_332',
    'Tambah Reservasi': 'tambah_reservasi_333',
    'Semua Tanggal': 'semua_tanggal_334',
    'Besok': 'besok_335',
    'Konfirmasi': 'konfirmasi_336',
    'Ubah ke Dikonfirmasi': 'ubah_ke_dikonfirmasi_337',
    'Kembalikan ke Menunggu': 'kembalikan_ke_menunggu_338',
    'Tandai Selesai': 'tandai_selesai_339',
    'Hapus Data': 'hapus_data_340',
    'Konfirmasi Pembatalan': 'konfirmasi_pembatalan_341',
    'Hapus Data Reservasi': 'hapus_data_reservasi_342',
    'Data reservasi ini akan dihapus secara permanen.': 'data_reservasi_ini_akan_343',
    'Belum Ada Reservasi': 'belum_ada_reservasi_344',
    'Reservasi dari web portal toko atau input manual kasir akan tampil di sini secara real-time.': 'reservasi_dari_web_portal_345',
    'Tambah Reservasi Manual': 'tambah_reservasi_manual_346',
    'Jumlah Tamu / Orang:': 'jumlah_tamu_orang_347',
    'Semua Cabang / Pusat': 'semua_cabang_pusat_348',
    'Pilih Layanan / Menu (Opsional):': 'pilih_layanan_menu_opsional_349',
    'Reservasi berhasil ditambahkan!': 'reservasi_berhasil_ditambahkan_350',
    'Simpan Reservasi': 'simpan_reservasi_351',
    'Nama Pelanggan *': 'nama_pelanggan_352',
    'Nomor WhatsApp / HP *': 'nomor_whatsapp_hp_353',
    'Tanggal *': 'tanggal_354',
    'Jam *': 'jam_355',
    'Cabang Toko': 'cabang_toko_356',
    'Layanan / Menu yang dipesan': 'layanan_menu_yang_dipesan_357',
    'Catatan Tambahan (Opsional)': 'catatan_tambahan_opsional_358',
    'Cari nama / nomor / layanan...': 'cari_nama_nomor_layanan_359',
    'misal: 081234567890': 'misal_081234567890_360',
    'misal: Potong Rambut + Catok / Paket Meja 4': 'misal_potong_rambut_catok_361',
    'misal: Stylist Mas Budi / Meja VIP': 'misal_stylist_mas_budi_362',
    'Layanan lokasi (GPS) tidak aktif.': 'layanan_lokasi_gps_tidak_363',
    'Silakan masukkan nama cabang': 'silakan_masukkan_nama_cabang_364',
    'Tentukan Titik Lokasi Cabang': 'tentukan_titik_lokasi_cabang_365',
    'Geser atau sentuh peta untuk memindahkan titik cabang': 'geser_atau_sentuh_peta_366',
    'Mencari lokasi perangkat...': 'mencari_lokasi_perangkat_367',
    'Simpan Cabang': 'simpan_cabang_368',
    'Nama Cabang': 'nama_cabang_369',
    'Radius Absensi Karyawan (Meter)': 'radius_absensi_karyawan_meter_370',
    'Contoh: Cabang Kemang, Cabang 2': 'contoh_cabang_kemang_cabang_371',
    '50 - 500': '50_500_372',
    'Kelola Cabang': 'kelola_cabang_373',
    'Nama Toko Utama': 'nama_toko_utama_374',
    'Edit Nama Toko': 'edit_nama_toko_375',
    'Nama toko diperbarui': 'nama_toko_diperbarui_376',
    'Salin Kode Toko': 'salin_kode_toko_377',
    'Tambah Cabang': 'tambah_cabang_378',
    'Kode Toko untuk Karyawan:': 'kode_toko_untuk_karyawan_379',
    'Belum ada cabang toko.': 'belum_ada_cabang_toko_380',
    'Hapus Cabang?': 'hapus_cabang_381',
    'Nama Toko': 'nama_toko_382',
    'Tambah Shift Baru': 'tambah_shift_baru_383',
    'Toleransi Telat (Menit)': 'toleransi_telat_menit_384',
    'Jadwal Shift': 'jadwal_shift_385',
    'Belum ada jadwal shift. Tambahkan minimal 1 shift (misal: Pagi 08:00 - 16:00).': 'belum_ada_jadwal_shift_386',
    'Tambah Shift': 'tambah_shift_387',
    'Pengaturan Pegawai': 'pengaturan_pegawai_388',
    'Pengaturan Absensi & Shift': 'pengaturan_absensi_shift_389',
    'Foto Absen Opsional': 'foto_absen_opsional_390',
    'Karyawan wajib foto saat ceklog (Hapus otomatis)': 'karyawan_wajib_foto_saat_391',
    'Mekanisme Jam Masuk Shift': 'mekanisme_jam_masuk_shift_392',
    'Karyawan tidak bisa absen di luar jadwal & toleransi telat': 'karyawan_tidak_bisa_absen_393',
    'Akses Fitur Karyawan': 'akses_fitur_karyawan_394',
    'Stok Opname Saat Tutup Shift': 'stok_opname_saat_tutup_395',
    'Wajib cek stok fisik saat tutup shift (fitur gudang)': 'wajib_cek_stok_fisik_396',
    'Kasir Input Total Uang (Laci Kasir)': 'kasir_input_total_uang_397',
    'Wajib input modal awal saat buka & tutup shift': 'wajib_input_modal_awal_398',
    'KDS (Kitchen Display System)': 'kds_kitchen_display_system_399',
    'Tampilkan layar pesanan untuk dapur': 'tampilkan_layar_pesanan_untuk_400',
    'Nama Shift (misal: Shift Pagi)': 'nama_shift_misal_shift_401',
    'Mulai (HH:mm)': 'mulai_hhmm_402',
    'Selesai (HH:mm)': 'selesai_hhmm_403',
    'Tunai (Cash) selalu aktif secara default. Aktifkan QRIS / Transfer sesuai kebutuhan toko.': 'tunai_cash_selalu_aktif_404',
    'QRIS Digital': 'qris_digital_405',
    'Terima pembayaran kode QRIS': 'terima_pembayaran_kode_qris_406',
    'Terima transfer rekening bank': 'terima_transfer_rekening_bank_407',
    'QR Code Portal Toko': 'qr_code_portal_toko_408',
    'Fitur edit menu QR belum tersedia.': 'fitur_edit_menu_qr_409',
    'Web Portal & Toko Online': 'web_portal_toko_online_410',
    'Halaman web publik toko untuk katalog menu digital dan booking reservasi pelanggan.': 'halaman_web_publik_toko_411',
    'Menu Digital QR Code': 'menu_digital_qr_code_412',
    'Pelanggan bisa scan QR untuk melihat daftar menu, foto & harga': 'pelanggan_bisa_scan_qr_413',
    'Reservasi Online': 'reservasi_online_414',
    'Salon/FnB/Jasa': 'salonfnbjasa_415',
    'Pelanggan dapat memesan jadwal layanan / booking meja via web': 'pelanggan_dapat_memesan_jadwal_416',
    'Program Membership': 'program_membership_417',
    'Loyalty': 'loyalty_418',
    'Kelola data member, poin loyalitas, dan promo khusus member': 'kelola_data_member_poin_419',
    'Tautan Web Toko berhasil disalin ke clipboard!': 'tautan_web_toko_berhasil_420',
    'Cetak QR Code': 'cetak_qr_code_421',
    'Buka Daftar Reservasi Masuk': 'buka_daftar_reservasi_masuk_422',
    'Logo Toko / Usaha': 'logo_toko_usaha_423',
    'Opsional': 'opsional_424',
    'Dicetak hitam-putih di nota thermal & tampil di web menu': 'dicetak_hitamputih_di_nota_425',
    'Mengunggah logo toko...': 'mengunggah_logo_toko_426',
    'Logo toko berhasil diperbarui!': 'logo_toko_berhasil_diperbarui_427',
    'Gagal mengunggah logo toko. Silakan coba lagi.': 'gagal_mengunggah_logo_toko_428',
    'Hapus Logo Toko?': 'hapus_logo_toko_429',
    'Logo toko tidak akan dicetak lagi pada nota dan tidak akan muncul di web menu.': 'logo_toko_tidak_akan_430',
    'Logo toko berhasil dihapus.': 'logo_toko_berhasil_dihapus_431',
    'Gagal menghapus logo toko.': 'gagal_menghapus_logo_toko_432',
    'Wajah terdeteksi & ter-zoom crop otomatis!': 'wajah_terdeteksi_terzoom_crop_433',
    'Wajah kurang jelas, foto di-crop ke area tengah.': 'wajah_kurang_jelas_foto_434',
    'Harap masukkan saldo awal kasir': 'harap_masukkan_saldo_awal_435',
    'Selfie wajib diambil untuk memulai shift': 'selfie_wajib_diambil_untuk_436',
    'Harap masukkan saldo akhir kas fisik di laci': 'harap_masukkan_saldo_akhir_437',
    'Input Stok Akhir Dapur': 'input_stok_akhir_dapur_438',
    'Harap isi semua sisa stok! Jika habis, ketik 0.': 'harap_isi_semua_sisa_439',
    'Format angka tidak valid pada salah satu bahan': 'format_angka_tidak_valid_440',
    'Simpan & Tutup Shift': 'simpan_tutup_shift_441',
    'Saldo Awal Kasir (Uang Tunai di Laci):': 'saldo_awal_kasir_uang_442',
    'Lokasi Anda belum tervalidasi di area cabang.': 'lokasi_anda_belum_tervalidasi_443',
    'Deteksi wajah...': 'deteksi_wajah_444',
    'Auto-Crop Wajah': 'autocrop_wajah_445',
    'Ajukan Izin Libur / Telat Masuk': 'ajukan_izin_libur_telat_446',
    'Rincian Keuangan Shift': 'rincian_keuangan_shift_447',
    'Kas Fisik di Laci Kasir': 'kas_fisik_di_laci_448',
    '(Saldo Awal + Penjualan Tunai)': 'saldo_awal_penjualan_tunai_449',
    '💡 QRIS & Transfer langsung masuk ke rekening bank/e-wallet, sehingga tidak dihitung di laci fisik kasir.': 'qris_transfer_langsung_masuk_450',
    'Hitung Uang Tunai di Laci & Masukkan Saldo Akhir:': 'hitung_uang_tunai_di_451',
    'Informasi Shift Kerja': 'informasi_shift_kerja_452',
    'Rp 0': 'rp_0_453',
    'Rp 0 (Uang Fisik Laci)': 'rp_0_uang_fisik_454',
    'Riwayat Stok & Opname': 'riwayat_stok_opname_455',
    'Belum ada riwayat stok': 'belum_ada_riwayat_stok_456',
    'Melebihi Batas Toleransi': 'melebihi_batas_toleransi_457',
    'Harga tidak boleh kosong untuk restock!': 'harga_tidak_boleh_kosong_458',
    'Bahan Baru': 'bahan_baru_459',
    'Manajemen Stok': 'manajemen_stok_460',
    'Wajibkan Opname Saat Tutup Shift': 'wajibkan_opname_saat_tutup_461',
    'Karyawan harus mengisi stok fisik sebelum shift ditutup.': 'karyawan_harus_mengisi_stok_462',
    'Peringatan Indikasi Fraud / Stok Aneh!': 'peringatan_indikasi_fraud_stok_463',
    'Restock': 'restock_464',
    'Opname': 'opname_465',
    'Wastage': 'wastage_466',
    'Total Harga Beli Awal (Rp)': 'total_harga_beli_awal_467',
    'Total Harga (Rp)': 'total_harga_rp_468',
    'Catatan / Alasan (Opsional)': 'catatan_alasan_opsional_469',
  };

  int filesChanged = 0;
  for (final entity in dir.listSync(recursive: true)) {
    if (entity is File && entity.path.endsWith('.dart')) {
      String content = entity.readAsStringSync();
      bool changed = false;
      
      for (final entry in stringToKey.entries) {
        final val = entry.key;
        final key = entry.value;
        
        final r1 = "Text('$val'";
        final r2 = 'Text("$val"';
        final target1 = "Text('$key'.tr(context: context)";
        final target2 = "Text('$key'.tr(context: context)";
        
        if (content.contains(r1)) { content = content.replaceAll(r1, target1); changed = true; }
        if (content.contains(r2)) { content = content.replaceAll(r2, target2); changed = true; }
        
        final r3 = "Text('$val',";
        final r4 = 'Text("$val",';
        final target3 = "Text('$key'.tr(context: context),";
        final target4 = "Text('$key'.tr(context: context),";
        
        if (content.contains(r3)) { content = content.replaceAll(r3, target3); changed = true; }
        if (content.contains(r4)) { content = content.replaceAll(r4, target4); changed = true; }
        
        final r5 = "Text('$val'))";
        final r6 = 'Text("$val"))';
        final target5 = "Text('$key'.tr(context: context)))";
        final target6 = "Text('$key'.tr(context: context)))";
        
        if (content.contains(r5)) { content = content.replaceAll(r5, target5); changed = true; }
        if (content.contains(r6)) { content = content.replaceAll(r6, target6); changed = true; }
      }
      
      if (changed) {
        entity.writeAsStringSync(content);
        filesChanged++;
      }
    }
  }
  print('Injected .tr(context: context) into $filesChanged files.');
}
